// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer><a>© 2025-2026 Matthew Kennedy</a><br><div class=\"badges\"><a href=\"https://artixlinux.org/\" target=\"_blank\" rel=\"noopener\"><img src=\"/static/badges/gnu-linux.gif\" alt=\"GNU/Linux\" width=\"88\" height=\"31\"></a> <a href=\"https://www.gnu.org/software/emacs/\" target=\"_blank\" rel=\"noopener\"><img src=\"/static/badges/createdwithemacs.png\" alt=\"Created with Emacs\" width=\"88\" height=\"31\"></a> <img src=\"/static/badges/no-ai.svg\" alt=\"No AI\" width=\"88\" height=\"31\"> <img src=\"/static/badges/made-by-hand.gif\" alt=\"Made by Hand\" width=\"88\" height=\"31\"> <a href=\"https://blog.matthew-kennedy.com/index.xml\" target=\"_blank\"><img src=\"/static/badges/rss.gif\" alt=\"RSS Feed\" width=\"88\" height=\"31\"></a> <a href=\"mailto:matthew@matthew-kennedy.com\"><img src=\"/static/badges/reply-via-email.gif\" alt=\"Reply via Email\" width=\"88\" height=\"31\"></a><br><a href=\"https://grapheneos.org\" target=\"_blank\" rel=\"noopener\"><img src=\"/static/badges/grapheneos.gif\" alt=\"GrapheneOS\" width=\"88\" height=\"31\"></a> <a href=\"https://kagi.com/smallweb\" target=\"_blank\" rel=\"noopener\"><img src=\"/static/badges/kagi.gif\" alt=\"Kagi Small Web\" width=\"88\" height=\"31\"></a> <a href=\"https://craftering.systemcrafters.net/@scc/previous\">←</a> <a href=\"https://craftering.systemcrafters.net/\">craftering</a> <a href=\"https://craftering.systemcrafters.net/@scc/next\">→</a></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
