// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\n\t\t\t\tbody {\n\t\t\t\t/* background-color: black; */\n\t\t\t\tbackground-color: #212121;\n\t\t\t\tcolor: white; /* make text visible */\n\t\t\t\tfont-family: sans-serif;\n\t\t\t\tmargin: 0;\n\t\t\t\tpadding: 1rem;\n\t\t\t\t}\n\t\t\t\th1 {\n\t\t\t\tdisplay: flex;\n\t\t\t\ttext-align: center;\n\t\t\t\tjustify-content: center;\n\t\t\t\t}\n\t\t\t\tnav {\n\t\t\t\tmargin: 1rem;\n\t\t\t\t}\n\t\t\t\tul {\n\t\t\t\tlist-style-type: none;\n\t\t\t\tmargin: 0;\n\t\t\t\tpadding: 0;\n\t\t\t\tdisplay: flex;\n\t\t\t\tjustify-content: center; \n\t\t\t\tgap: 1rem;              \n\t\t\t\t}\n\t\t\t\tul li {\n\t\t\t\tfloat: none;           \n\t\t\t\t}\n\t\t\t\tul li a {\n\t\t\t\tdisplay: block;\n\t\t\t\tcolor: white;\n\t\t\t\ttext-align: center;\n\t\t\t\tpadding: 14px 16px;\n\t\t\t\ttext-decoration: none;\n\t\t\t\t}\n\t\t</style><nav><div class=\"nav-links\"><ul><li><a href=\"/\">Home</a></li><li><a href=\"http://localhost:1313\">Blog</a></li><li><a href=\"http://localhost:1313/posts/now\">Now</a></li><li><a href=\"/about\">About</a></li><li><a href=\"/micro\">Reel</a></li><li><a href=\"/photos\">Photos</a></li><li><a href=\"/music\">Tunes</a></li></ul></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
