// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "codeberg.org/Matthew-K310/matthew-kennedy/components"

func Links() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Links | Matthew Kennedy</title><link rel=\"stylesheet\" href=\"/static/css/styles.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.NavBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"text-block\"><em>Note: These links lead to the RSS feeds of the respective media, rather than the page to read/watch/listen to them.</em><h1>Friend's Sites</h1><ul><li><a href=\"https://joshblais.com\">Joshua Blais</a></li><li><a href=\"https://joshblais.com\">cashmere</a></li><li><a href=\"https://linuxmaxxing.com/\">Scotty</a></li><li><a href=\"https://マリウス.com/\">Marius (マリウス)</a></li><li><a href=\"https://joshtronic.com/\">Josh Sherman</a></li><li><a href=\"https://pierolescano.com/\">Piero Lescano</a></li><li><a href=\"https://brookjeynes.dev/\">Brook Jeynes</a></li></ul><h1>Collections</h1><h2>Reading</h2>My written RSS feeds.<br><b>Coming soon...</b><h2>Watching</h2>My visual RSS feeds/the channels I frequent.<br><b>Coming soon...</b><h2>Podcasts</h2>The sound of my commutes and projects.<ul><li><a href=\"https://rss.buzzsprout.com/2533607.rss\">Acceptable Losses: A Grimdark Podcast</a></li><li><a href=\"https://rss.buzzsprout.com/1497970.rss\">Adeptus Ridiculous</a></li><li><a href=\"https://media.rss.com/linkarzu/feed.xml\">Linkarzu</a></li><li><a href=\"https://feeds.transistor.fm/rally-caps\">Rally Caps</a></li><li><a href=\"https://feeds.megaphone.fm/TNL8747838853\">Tape Notes</a></li><li><a href=\"https://anchor.fm/s/149fd51c/podcast/rss\">Tech Over Tea</a></li><li><a href=\"https://feeds.megaphone.fm/RSV6952153075\">The Brett Cooper Show</a></li><li><a href=\"https://feeds.megaphone.fm/LMG3928170156\">The WAN Show</a></li><li><a href=\"https://feeds.megaphone.fm/STU4418364045\">Waveform: The MKBHD Podcast</a></li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
