// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "codeberg.org/Matthew-K310/matthew-kennedy/components"

func Now() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Now | Matthew Kennedy</title><link rel=\"stylesheet\" href=\"/static/css/styles.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.NavBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"text-block\"><header><h1>Now</h1></header><p>You should make a <a href=\"https://nownownow.com/\">Now page</a>.</p><section><div><h2>Projects</h2></div><div><ul><li>Making a game for the <a href=\"https://itch.io/jam/gamedevtv-jam-2026\">GameDev.tv Game Jam</a></li><li>Working on a FOSS, federated Goodreads alternative.</li><li>Hacking on my <a href=\"https://codeberg.org/Matthew-K310/.emacs.d.git\">Emacs configuration.</a></li></ul></div></section><section><div><h2>Reading</h2></div><div><ul><li>Colossians - Bible study</li><li>Ecclesiastes - Bible reading</li><li>Hunger Games<br><a>Suzanne Collins - Science(?) Fiction</a></li></ul></div></section><section><div><h2>Listening</h2></div><div><p>I am a huge music fan, and I've been doing music production off and on since 2020, so music really means a lot to me. These are just a few of the albums I've been enjoying as of late.</p><div><h3>Work & Focus</h3><p>I blame <a href=\"https://joshblais.com/blog/productivity-hack-music/\">Joshua Blais</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("for")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/now.templ`, Line: 66, Col: 110}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " starting me down this path.</p><ul><li>Katana ZERO (Original Soundtrack)</li><li>FTL: Faster Than Light - Original Soundtrack</li><li>Endless Space 2 - Original Soundtrack</li></ul></div><div><h3>Leisure Listening</h3><ul><li>Halo: Combat Evolved - Original Soundtrack</li><li>Assassins Creed IV: Black Flag - Original Soundtrack</li><li>Hotline Miami 2: Wrong Number Sountrack</li></ul></div></div></section><section><div><h2>Learning</h2></div><div><ul><li>Emacs and Elisp</li><li>Zig</li><li>Raylib (specifically <a href=\"https://github.com/raylib-zig/raylib-zig\">raylib-zig</a>)</li></ul></div></section><section><div><h2>Watching</h2><p>I haven't found modern TV to be all that interesting at this point, so this list will likely be empty for quite some time.</p></div></section><section><div><h2>Playing</h2><p>I've started to get back into gaming in the form of playing some older single-player games that I missed out on when I was younger. These fill the story-hungry void left by modern television.</p></div><div><ul><li>The Mass Effect Trilogy (currently on Mass Effect 2 and am quite enthralled)</li><li>Assassin's Creed IV: Black Flag</li><li>Assassin's Creed III</li><li>Outer Wilds (for the relaxing gaming sessions)</li></ul></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
