// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Matthew-K310/matthew-kennedy/components"

func Now() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Now | Matthew Kennedy</title><link rel=\"stylesheet\" href=\"/static/css/styles.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.NavBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"text-block\"><header><h1>Now</h1></header><p>You should make a <a href=\"https://nownownow.com/\">Now page</a>.</p><section><div><h2>Projects</h2></div><div><ul><li>Creating a website ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("for")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/now.templ`, Line: 28, Col: 34}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " a crafts business to showcase and sell their handmade goods online</li><li>Making small updates to <a href=\"https://codeberg.org/Matthew-K310/bases.el\">bases.el</a></li><li>Starting up work on <a href=\"https://codeberg.org/Matthew-K310/emacs-xmpp\">emacs-xmpp</a>. Help wanted with OMEMO implementation in Go.</li></ul></div></section><section><div><h2>Reading</h2></div><div><div><h3>The Book of Amos</h3><p>Biblical studies</p><p>Taking a week ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("for")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/now.templ`, Line: 47, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " focused study of the first chapter. It's been good - yet odd - so far. More updates to follow.</p></div><div><h3>The Hobbit</h3><p>J.R.R. Tolkien · Fantasy</p><p>This is one of the books I've read the most, having done so around 2-3 dozen times since I was 8 or 9 years old. Tolkien truly was a master of worldbuilding and character development, and I look forward to getting further up and further in.</p></div><p>See my <a href=\"https://blog.matthew-kennedy.com/posts/20260128t113417--2026-reading-list__blog_reading/\">2026 reading list</a> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("for")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/now.templ`, Line: 65, Col: 19}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, " the full list.</p></div></section><section><div><h2>Listening</h2></div><div><p>I am a huge music fan, and I've been doing music production off and on since 2020, so music really means a lot to me. These are just a few of the albums I've been enjoying as of late.</p><div><h3>Work & Focus</h3><p>I've been on a huge video game soundtrack kick lately (I blame <a href=\"https://joshuablais.com\">Joshua Blais</a>).</p><ul><li>Age of Empires II: Definitive Edition</li><li>Stellaris OST</li><li>Warhammer 40,000: Rogue Trader OST</li></ul></div><div><h3>Leisure Listening</h3><p>Currently rotating through various artists and genres</p><ul><li>A Wave, Across The Sea - Arcane Roots</li><li>Escape From Solemnace - Matthew Kennedy</li><li>Strange Trails - Lord Huron</li><li>ANYWHERE HERE IS PERFECT - Sam Gellaitry</li></ul></div></div></section><section><div><h2>Learning</h2></div><div><ul><li>The Zig programming language</li><li>American Sign Lanugage</li></ul></div></section><section><div><h2>Watching</h2></div><ul><li>Fallout, Season 2</li><li>Catching up on the WarhammerTV shows</li><li>24, Season 5</li></ul><div></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
